version: "3"

services:
  server:
    build: .
    command: "/bin/app --server --addrs=:9090"
    ports:
      - 9090:9090

  recver:
    build: .
    command: "/bin/app --addrs=server:9090"
    depends_on:
      - server

  sender:
    build: .
    command: "/bin/app --addrs=server:9090 --sender"
    depends_on:
      - server
      - recver

  redis:
    image: redis:6.0.5-alpine3.12
    ports:
      - 6379:6379
