// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bus.proto

package buffs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("bus.proto", fileDescriptor_e9aee8707d5a25b8)
}

var fileDescriptor_e9aee8707d5a25b8 = []byte{
	// 47 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2a, 0x2d, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2a, 0x4d, 0x4b, 0x2b, 0x4e, 0x62, 0x03, 0xf3,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x34, 0x9f, 0x1d, 0x1a, 0x00, 0x00, 0x00,
}
